import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Courses sidebar — auto-generated from the courses/ folder structure.
const sidebars: SidebarsConfig = {
  courses: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
