import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Knowledge Base sidebar — auto-generated from the docs/ folder structure.
 * Each KB category lives in its own folder with a _category_.json file.
 */
const sidebars: SidebarsConfig = {
  knowledgeBase: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
