import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// BKU Student Guide sidebar — auto-generated from the guide/ folder structure.
const sidebars: SidebarsConfig = {
  guide: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
